-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * (100 - C.DISCOUNT_RATE)/100 * 30) AS FEE

FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID

JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE = C.CAR_TYPE

WHERE B.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE B.START_DATE <= '2022-11-30' AND B.END_DATE >= '2022-11-01') AND C.DURATION_TYPE = '30일 이상'

GROUP BY A.CAR_ID
HAVING A.CAR_TYPE IN ('SUV', '세단') AND (FEE >= 500000 AND FEE < 2000000)

ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC
