-- 코드를 작성해주세요
WITH FRONTEND_SKILLS AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT B.ID, B.EMAIL, B.FIRST_NAME, B.LAST_NAME
FROM FRONTEND_SKILLS A
JOIN DEVELOPERS B
ON A.CODE & B.SKILL_CODE
ORDER BY B.ID